# Альтернативные варианты исправления проблемы с walk-forward

# ============================================================================
# ВАРИАНТ 3: Сократить testing_period_days (чтобы testing_end <= end_date)
# ============================================================================
# walk_forward:
#   start_date: "2022-06-01"  
#   end_date: "2022-06-30"
#   training_period_days: 60   
#   testing_period_days: 29    # ИСПРАВЛЕНО: сократили с 30 до 29 дней
#                              # testing_end = 2022-06-01 + 29 = 2022-06-30 ✓

# ============================================================================
# ВАРИАНТ 4: Сдвинуть start_date раньше
# ============================================================================
# walk_forward:
#   start_date: "2022-05-31"  # ИСПРАВЛЕНО: сдвинули на 1 день раньше
#   end_date: "2022-06-30"    # testing_end = 2022-05-31 + 30 = 2022-06-30 ✓
#   training_period_days: 60   
#   testing_period_days: 30    

# ============================================================================
# ВАРИАНТ 5: Использовать настройки из demo_timing.yaml (работающий вариант)
# ============================================================================
# walk_forward:
#   start_date: "2022-04-15"  # Раньше начинаем  
#   end_date: "2022-06-30"    # Больше запаса
#   training_period_days: 30   # Сократили обучение
#   testing_period_days: 15    # Сократили тест
#                              # Много шагов: 2022-04-15, 2022-04-30, 2022-05-15, 2022-05-30, 2022-06-14

# ============================================================================
# ТЕКУЩИЙ ВЫБОР: Вариант 2 - продлили end_date до 2022-07-01
# ============================================================================

data_dir: "data_clean"
results_dir: "results"
portfolio:
  initial_capital: 1000.0
  risk_per_position_pct: 0.01
  max_active_positions: 15

pair_selection:
  lookback_days: 60
  coint_pvalue_threshold: 0.05
  ssd_top_n: 5000
  min_half_life_days: 1
  max_half_life_days: 10
  min_mean_crossings: 8

backtest:
  timeframe: "15min"
  rolling_window: 30
  zscore_threshold: 1.5
  zscore_exit: 0.5
  stop_loss_multiplier: 3.0
  fill_limit_pct: 0.1
  commission_pct: 0.004
  slippage_pct: 0.002
  annualizing_factor: 365
  cooldown_hours: 4

walk_forward:
  start_date: "2022-06-01"
  end_date: "2022-07-01"    # ВАРИАНТ 2: продлили на 1 день
  training_period_days: 60
  testing_period_days: 30

max_shards: null 