data_dir: "data_clean"
results_dir: "results"
portfolio:
  initial_capital: 1000.0
  risk_per_position_pct: 0.01  # Риск 1% на сделку
  max_active_positions: 15  # Торгуем не более 10 пар одновременно
pair_selection:
  lookback_days: 60
  coint_pvalue_threshold: 0.05  # Немного ослабили для демо (но все еще строже исходного)
  ssd_top_n: 5000  # Резко сократили с 10000 до 150
  min_half_life_days: 1  # 1 день минимум 
  max_half_life_days: 10   # Увеличили немного до 10 дней для демо
  min_mean_crossings: 8    # Вернули к 8 для демо
backtest:
  timeframe: "15min"
  rolling_window: 30
  zscore_threshold: 1.5     # Увеличили с 1.5 до 2.5!
  zscore_exit: 0.5         # Добавим порог выхода
  stop_loss_multiplier: 3.0 # Увеличили с 3.0 до 4.0
  fill_limit_pct: 0.1       # Строже: было 0.2
  commission_pct: 0.004     # Реальная комиссия Binance taker ~0.04%
  slippage_pct: 0.002       # Реальное проскальзывание ~0.02%
  annualizing_factor: 365
  cooldown_hours: 4         # Новый параметр: тайм-аут после выхода
walk_forward:
  start_date: "2022-06-01"  # Короткий период для демо 
  end_date: "2022-07-01"    # ИСПРАВЛЕНО: продлили на 1 день для корректного тестового окна
  training_period_days: 60   # Увеличили training период
  testing_period_days: 30    # Увеличили testing период
max_shards: null
  
